openapi: 3.2.0
info:
  title: Factorial Core::Me API
  description: 'Open Api Specifications available at https://github.com/factorialco/oas


    Guides and support available at https://help.factorialhr.com/integrations


    # Authentication


    The public API provides two methods of authentication, ApiKeys and OAuth2.'
  version: 1.0.0
servers:
- url: https://api.factorialhr.com/api
- url: https://api.demo.factorialhr.com/api
security:
- oauth2: []
- apikey: []
tags:
- name: Core::Me
paths:
  /v1/me:
    get:
      tags:
      - Core::Me
      summary: Get Information About Current User
      operationId: getCurrentUser
      description: After token grant, get information of the token holder
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          refreshUrl: /oauth/token
          scopes:
            read: Required for all operations
            write: Required for write operations
    apikey:
      type: apiKey
      in: header
      name: x-api-key
